
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Apr 04 16:21:05 CEST 2006
//----------------------------------------------------

package sej.loader.excel;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONCAT = 8;
  public static final int GREATEROREQUAL = 19;
  public static final int NOTEQUAL = 17;
  public static final int LPAREN = 12;
  public static final int GREATER = 18;
  public static final int INT = 34;
  public static final int PRODUCT = 27;
  public static final int LESS = 20;
  public static final int MINUS = 3;
  public static final int MATCH = 31;
  public static final int RPAREN = 13;
  public static final int NOT = 25;
  public static final int AND = 23;
  public static final int OR = 24;
  public static final int COMMA = 9;
  public static final int DIV = 5;
  public static final int LESSOREQUAL = 21;
  public static final int PLUS = 2;
  public static final int MIN = 29;
  public static final int IF = 22;
  public static final int EXP = 6;
  public static final int EOF = 0;
  public static final int EQUAL = 16;
  public static final int error = 1;
  public static final int PERCENT = 7;
  public static final int IDENT = 37;
  public static final int LBRACK = 14;
  public static final int TIMES = 4;
  public static final int COLON = 10;
  public static final int INDEX = 32;
  public static final int RBRACK = 15;
  public static final int DOLLAR = 11;
  public static final int DBL = 35;
  public static final int SUM = 26;
  public static final int STRING = 36;
  public static final int AVERAGE = 28;
  public static final int MAX = 30;
  public static final int ROUND = 33;
}

